"""initial schema: part_numbers and lots tables

Revision ID: f13a18a4211f
Revises: 
Create Date: 2026-09-11 19:11:20.625107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13a18a4211f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_numbers',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_part_numbers_code'), 'part_numbers', ['code'], unique=False)
    op.create_table('lots',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('part_number_code', sa.String(), nullable=False),
    sa.Column('product_family', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('audited_by_first_name', sa.String(), nullable=True),
    sa.Column('audited_by_last_name', sa.String(), nullable=True),
    sa.Column('audited_by_system_user', sa.String(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['part_number_code'], ['part_numbers.code'], ),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('lot_id', 'part_number_code', name='uq_lot_part_number')
    )
    op.create_index(op.f('ix_lots_lot_id'), 'lots', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lots',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('part_number', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('product_family', sa.VARCHAR(), nullable=False),
    sa.Column('units', sa.INTEGER(), nullable=False),
    sa.Column('manufacturing_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('audited_by_first_name', sa.VARCHAR(), nullable=True),
    sa.Column('audited_by_last_name', sa.VARCHAR(), nullable=True),
    sa.Column('audited_by_system_user', sa.VARCHAR(), nullable=True),
    sa.Column('audited_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Lots_id'), 'Lots', ['id'], unique=False)
    op.drop_index(op.f('ix_lots_lot_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_part_numbers_code'), table_name='part_numbers')
    op.drop_table('part_numbers')
    # ### end Alembic commands ###
